Traceback (most recent call last):
  File "/home/sano_anju/01/sample/KeyError/k01.py", line 9, in <module>
    print(d[b])
          ~^^^
KeyError: 6